# Generated by Django 4.2.4 on 2023-08-23 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_cat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.categories', verbose_name='Порода'),
        ),
    ]
