# Generated by Django 4.2.4 on 2023-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_alter_categories_options_alter_cat_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Имя'),
        ),
    ]
