# Generated by Django 4.2.4 on 2023-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0007_alter_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Фото'),
        ),
    ]
