# Generated by Django 4.2.4 on 2023-09-01 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0008_categories_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Фото'),
        ),
    ]
